language: php

php:
  - 5.6
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - touch storage/testing.sqlite
  - composer install -n --prefer-dist
  - php artisan migrate --database=sqlite_testing --force
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run
