language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_script:
  - composer self-update
  - touch storage/testing.sqlite
  - composer install -n --prefer-dist
  - php artisan migrate --env=testing
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run